#!/usr/bin/perl

open(LOGFILE, ">AdjustIoBuildLogFile.txt");
print LOGFILE "Perl script started\n";
close (LOGFILE);
open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "Perl version:".`perl --version`."\n";
close (LOGFILE);
open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "Python version:".`python --version 2>&1`."\n";
close (LOGFILE);

$installPath = $ARGV[0];
open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "InstallPath: ".$installPath."\n";
close (LOGFILE);

$currDir = `pwd`;
open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "CurrDir: ".$currDir."\n";
close (LOGFILE);

chomp $currDir; 
open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "Chomped: ".$currDir."\n";
close (LOGFILE);

open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "Opening python script:\n";
print LOGFILE $currDir."/Assets/AdjustIo/PostbuildScripts/AdjustIoRunner.py"."\n";
close (LOGFILE);

$iPhonePath = `xcodebuild -version -sdk | grep ^Path | grep iPhoneOS | tail -n 1 | cut -c 7-`;
chomp $iPhonePath;


# AdjustIoRunner.py will add the necessary libraries to the xcode project
`python2.6 \'$currDir/Assets/AdjustIo/Data/PostbuildScripts/AdjustIoRunner.py\' \'$installPath\' \'$currDir/Assets/AdjustIo/Data/\' \'$iPhonePath\' `;

open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "python script done\n";
close (LOGFILE);

open(LOGFILE, ">>AdjustIoBuildLogFile.txt");
print LOGFILE "enabling objective c exceptions\n";
close (LOGFILE);

open (PBXPROJ , "<$installPath/Unity-iPhone.xcodeproj/project.pbxproj");
my @lines = <PBXPROJ>; 		
close(PBXPROJ);

open (PBXPROJ , ">$installPath/Unity-iPhone.xcodeproj/project.pbxproj");
foreach(@lines){
	$line = $_;
	print SOURCEFILE $line;
	if( $line =~ /.*GCC_ENABLE_OBJC_EXCEPTIONS = NO;.*/ ){
		print PBXPROJ "\t\t\t\tGCC_ENABLE_OBJC_EXCEPTIONS = YES;\n";
	}else{
		print PBXPROJ $line;
	}
}
close (PBXPROJ);
